package com.sweyla.gustavla.alone;

public class City extends Map {

	public int getMainWalkableTex() {
		return 3;
	}
	
	public int getMainWallTex() {
		return 1;
	}
	
	public String getName() {
		return "CITY";
	}
	
	public void resetEntities() {
		super.resetEntities();
		
		//Entity[] will_add = new Entity[10];
		//int c = 0;
		
		// Create some friendly NPCs
		for (int i=0; i<getWidth(); ++i) {
			for (int j=0; j<getHeight(); ++j) {
				// manhattan distance will do
				int dist = distanceToHero(i, j); 
				if (getTile(i, j).isWalkable() && dist > 2) {
					// Check if it's conflicting with other entities
					
					boolean ok = true;
					for (Entity e : getEntities()) {
						if (e != null) {
							if (getTileRectangle(i, j).intersects(e.getRectangle())) {
								ok = false;
								break;
							}
						}
					}
					
					if (ok) {
						if (Math.random() > 0.95) {
							NPC npc = new NPC(engine);
							npc.friendly = true;
							npc.setTilePos(i, j);
							addEntity(npc);
						}
					}
				}
			}
		}
	}
	
	
	public City(Engine engine, int width, int height) {
		// Generated by Python. I'm a bit new to Java, so I don't want to start parsing in Java
		super(engine, 33, 15);
		{ Tile t = getTile(0, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(4, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(6, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(8, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(9, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(10, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(11, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(12, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(13, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(14, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(15, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(16, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(17, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(18, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(19, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(20, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(21, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(22, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(23, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(24, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(25, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(26, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(27, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(28, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(29, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(30, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(31, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(32, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(4, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(6, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(8, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(9, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(10, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(11, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(12, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(13, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(14, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(15, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(16, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(17, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(18, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(19, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(20, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(21, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(22, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(23, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(24, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(25, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(26, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(27, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(28, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(29, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(30, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(31, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(32, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(4, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(6, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(8, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(9, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(10, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(11, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(12, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(13, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(14, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(15, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(16, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(17, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(18, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(19, 2); t.tex = 6; t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(19, 2); addEntity(unit); }
		{ Tile t = getTile(20, 2); t.tex = 6; t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(20, 2); addEntity(unit); }
		{ Tile t = getTile(21, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(22, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(23, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(24, 2); t.tex = 6; t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(24, 2); addEntity(unit); }
		{ Tile t = getTile(25, 2); t.tex = 6; t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(25, 2); addEntity(unit); }
		{ Tile t = getTile(26, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(27, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(28, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(29, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(30, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(31, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(32, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(4, 3); t.tex = 6; t.walkable = true; Weapon unit = new Weapon(engine); unit.setTilePos(4, 3); addItem(unit); unit.setType(4); }
		{ Tile t = getTile(5, 3); t.tex = 6; t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(5, 3); addEntity(unit); }
		{ Tile t = getTile(6, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(8, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(9, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(10, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(11, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(12, 3); t.tex = 6; t.walkable = true; NPC unit = new NPC(engine); unit.setTilePos(12, 3); addEntity(unit); }
		{ Tile t = getTile(13, 3); t.tex = 6; t.walkable = true; }
		{ Tile t = getTile(14, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(15, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(16, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(17, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(18, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(19, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(20, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(21, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(22, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(23, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(24, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(25, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(26, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(28, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(29, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(30, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(31, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(32, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 4); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(4, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 4); t.tex = 6; t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(5, 4); addEntity(unit); }
		{ Tile t = getTile(6, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 4); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 4); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(9, 4); t.tex = 6; t.walkable = true; }
		{ Tile t = getTile(10, 4); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(11, 4); t.tex = 6; t.walkable = true; }
		{ Tile t = getTile(12, 4); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(13, 4); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(14, 4); t.tex = 44; t.walkable = false; }
		{ Tile t = getTile(15, 4); t.tex = 12; t.walkable = false; }
		{ Tile t = getTile(16, 4); t.tex = 12; t.walkable = false; }
		{ Tile t = getTile(17, 4); t.tex = 12; t.walkable = false; }
		{ Tile t = getTile(18, 4); t.tex = 12; t.walkable = false; }
		{ Tile t = getTile(19, 4); t.tex = 45; t.walkable = false; }
		{ Tile t = getTile(20, 4); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(21, 4); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(22, 4); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(23, 4); t.tex = 44; t.walkable = false; }
		{ Tile t = getTile(24, 4); t.tex = 12; t.walkable = false; }
		{ Tile t = getTile(25, 4); t.tex = 45; t.walkable = false; }
		{ Tile t = getTile(26, 4); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(28, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(29, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(30, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(31, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(32, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 5); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 5); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(2, 5); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(3, 5); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(4, 5); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 5); t.tex = 6; t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(5, 5); addEntity(unit); }
		{ Tile t = getTile(6, 5); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 5); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(8, 5); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(9, 5); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 5); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(11, 5); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(12, 5); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(13, 5); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(14, 5); t.tex = 42; t.walkable = false; }
		{ Tile t = getTile(15, 5); t.tex = 10; t.tex2 = 11; t.walkable = true; t.transport_to_map = 5;
		t.transport_to_tile_x = 3; t.transport_to_tile_y = 3; t.transport_facing = 3; }
		{ Tile t = getTile(16, 5); t.tex = 10; t.walkable = false; }
		{ Tile t = getTile(17, 5); t.tex = 10; t.walkable = false; }
		{ Tile t = getTile(18, 5); t.tex = 10; t.tex2 = 11; t.walkable = true; t.transport_to_map = 5;
		t.transport_to_tile_x = 9; t.transport_to_tile_y = 3; t.transport_facing = 3; }
		{ Tile t = getTile(19, 5); t.tex = 43; t.walkable = false; }
		{ Tile t = getTile(20, 5); t.tex = getMainWalkableTex(); t.walkable = true; NPC unit = new NPC(engine); unit.setTilePos(20, 5); addEntity(unit); }
		{ Tile t = getTile(21, 5); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(22, 5); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(23, 5); t.tex = 42; t.walkable = false; }
		{ Tile t = getTile(24, 5); t.tex = 10; t.tex2 = 11; t.walkable = true; t.transport_to_map = 6;
		t.transport_to_tile_x = 3; t.transport_to_tile_y = 3; t.transport_facing = 3; }
		{ Tile t = getTile(25, 5); t.tex = 43; t.walkable = false; }
		{ Tile t = getTile(26, 5); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 5); t.tex = 6; t.walkable = true; }
		{ Tile t = getTile(28, 5); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(29, 5); t.tex = 1; t.tex2 = 11; t.walkable = true; t.transport_to_map = 3;
		t.transport_to_tile_x = 15; t.transport_to_tile_y = 28; t.transport_facing = 3; }
		{ Tile t = getTile(30, 5); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(31, 5); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(32, 5); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 6); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 6); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(2, 6); t.tex = getMainWalkableTex(); t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(2, 6); addEntity(unit); }
		{ Tile t = getTile(3, 6); t.tex = getMainWalkableTex(); t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(3, 6); addEntity(unit); }
		{ Tile t = getTile(4, 6); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 6); t.tex = 6; t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(5, 6); addEntity(unit); }
		{ Tile t = getTile(6, 6); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 6); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(9, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(11, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(12, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(13, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(14, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(15, 6); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(16, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(17, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(18, 6); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(19, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(20, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(21, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(22, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(23, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(24, 6); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(25, 6); t.tex = getMainWalkableTex(); t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(25, 6); addEntity(unit); }
		{ Tile t = getTile(26, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 6); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(28, 6); t.tex = 6; t.walkable = true; }
		{ Tile t = getTile(29, 6); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(30, 6); t.tex = 6; t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(30, 6); addEntity(unit); }
		{ Tile t = getTile(31, 6); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(32, 6); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(0, 7); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 7); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(2, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 7); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 7); t.tex = 6; t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(5, 7); addEntity(unit); }
		{ Tile t = getTile(6, 7); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 7); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(9, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(11, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(12, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(13, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(14, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(15, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(16, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(17, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(18, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(19, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(20, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(21, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(22, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(23, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(24, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(25, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(26, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(28, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(29, 7); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(30, 7); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(31, 7); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(32, 7); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(0, 8); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(2, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 8); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 8); t.tex = 6; t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(5, 8); addEntity(unit); }
		{ Tile t = getTile(6, 8); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 8); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(8, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(9, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 8); t.tex = 44; t.walkable = false; }
		{ Tile t = getTile(11, 8); t.tex = 12; t.walkable = false; }
		{ Tile t = getTile(12, 8); t.tex = 12; t.walkable = false; }
		{ Tile t = getTile(13, 8); t.tex = 45; t.walkable = false; }
		{ Tile t = getTile(14, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(15, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(16, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(17, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(18, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(19, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(20, 8); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(21, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(22, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(23, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(24, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(25, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(26, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(28, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(29, 8); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(30, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(31, 8); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(32, 8); t.tex = getMainWalkableTex(); t.walkable = true; t.transport_to_map = 2;
		t.transport_to_tile_x = 1; t.transport_to_tile_y = 40; t.transport_facing = 2; }
		{ Tile t = getTile(0, 9); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 9); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(2, 9); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 9); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(4, 9); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 9); t.tex = 6; t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(5, 9); addEntity(unit); }
		{ Tile t = getTile(6, 9); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 9); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 9); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(9, 9); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 9); t.tex = 42; t.walkable = false; }
		{ Tile t = getTile(11, 9); t.tex = 10; t.walkable = false; }
		{ Tile t = getTile(12, 9); t.tex = 10; t.tex2 = 11; t.walkable = true; t.transport_to_map = 4;
		t.transport_to_tile_x = 3; t.transport_to_tile_y = 3; t.transport_facing = 3; }
		{ Tile t = getTile(13, 9); t.tex = 43; t.walkable = false; }
		{ Tile t = getTile(14, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(15, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(16, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(17, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(18, 9); t.tex = 2; t.walkable = true; NPC unit = new NPC(engine); unit.setTilePos(18, 9); addEntity(unit); }
		{ Tile t = getTile(19, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(20, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(21, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(22, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(23, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(24, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(25, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(26, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(27, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(28, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(29, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(30, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(31, 9); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(32, 9); t.tex = 2; t.walkable = true; t.transport_to_map = 2;
		t.transport_to_tile_x = 1; t.transport_to_tile_y = 41; t.transport_facing = 2; }
		{ Tile t = getTile(0, 10); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(2, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(6, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(7, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(9, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 10); t.tex = getMainWalkableTex(); t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(10, 10); addEntity(unit); }
		{ Tile t = getTile(11, 10); t.tex = getMainWalkableTex(); t.walkable = true; NPC unit = new NPC(engine); unit.setTilePos(11, 10); addEntity(unit); }
		{ Tile t = getTile(12, 10); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(13, 10); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(14, 10); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(15, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(16, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(17, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(18, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(19, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(20, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(21, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(22, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(23, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(24, 10); t.tex = getMainWalkableTex(); t.walkable = true; NPC unit = new NPC(engine); unit.setTilePos(24, 10); addEntity(unit); }
		{ Tile t = getTile(25, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(26, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 10); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(28, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(29, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(30, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(31, 10); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(32, 10); t.tex = getMainWalkableTex(); t.walkable = true; t.transport_to_map = 2;
		t.transport_to_tile_x = 1; t.transport_to_tile_y = 42; t.transport_facing = 2; }
		{ Tile t = getTile(0, 11); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 11); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(2, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(6, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(7, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(9, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(11, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(12, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(13, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(14, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(15, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(16, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(17, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(18, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(19, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(20, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(21, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(22, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(23, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(24, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(25, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(26, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 11); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(28, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(29, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(30, 11); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(31, 11); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(32, 11); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(0, 12); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(1, 12); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(2, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(6, 12); t.tex = getMainWalkableTex(); t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(6, 12); addEntity(unit); }
		{ Tile t = getTile(7, 12); t.tex = getMainWalkableTex(); t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(7, 12); addEntity(unit); }
		{ Tile t = getTile(8, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(9, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(11, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(12, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(13, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(14, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(15, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(16, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(17, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(18, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(19, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(20, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(21, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(22, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(23, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(24, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(25, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(26, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 12); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(28, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(29, 12); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(30, 12); t.tex = getMainWalkableTex(); t.walkable = true; Stone unit = new Stone(engine); unit.setTilePos(30, 12); addEntity(unit); }
		{ Tile t = getTile(31, 12); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(32, 12); t.tex = 15; t.walkable = false; }
		{ Tile t = getTile(0, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(1, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(2, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(3, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(4, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(5, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(6, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(7, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(8, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(9, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(10, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(11, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(12, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(13, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(14, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(15, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(16, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(17, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(18, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(19, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(20, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(21, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(22, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(23, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(24, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(25, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(26, 13); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(27, 13); t.tex = 2; t.walkable = true; }
		{ Tile t = getTile(28, 13); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(29, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(30, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(31, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(32, 13); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(0, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(1, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(2, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(3, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(4, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(5, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(6, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(7, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(8, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(9, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(10, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(11, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(12, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(13, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(14, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(15, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(16, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(17, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(18, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(19, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(20, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(21, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(22, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(23, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(24, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(25, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(26, 14); t.tex = getMainWalkableTex(); t.walkable = true; t.transport_to_map = 1;
		t.transport_to_tile_x = 30; t.transport_to_tile_y = 1; t.transport_facing = 1; }
		{ Tile t = getTile(27, 14); t.tex = 2; t.walkable = true; t.transport_to_map = 1;
		t.transport_to_tile_x = 31; t.transport_to_tile_y = 1; t.transport_facing = 1; }
		{ Tile t = getTile(28, 14); t.tex = getMainWalkableTex(); t.walkable = true; t.transport_to_map = 1;
		t.transport_to_tile_x = 32; t.transport_to_tile_y = 1; t.transport_facing = 1; }
		{ Tile t = getTile(29, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(30, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(31, 14); t.tex = 7; t.walkable = false; }
		{ Tile t = getTile(32, 14); t.tex = 7; t.walkable = false; }
	}
}
