package com.sweyla.gustavla.alone;

public class HouseLong extends Map {

	public String getName() {
		return "HOUSE";
	}
	
	public HouseLong(Engine engine, int width, int height) {
		// Generated by Python. I'm a bit new to Java, so I don't want to start parsing in Java
		super(engine, 12, 5);
		{ Tile t = getTile(0, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(4, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(6, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(8, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(9, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(10, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(11, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(2, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(6, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(9, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(11, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(2, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(6, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(7, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(9, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(11, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(2, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(6, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(8, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(9, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(10, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(11, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 4); t.tex = getMainWalkableTex(); t.walkable = true; t.transport_to_map = 0;
		t.transport_to_tile_x = 15; t.transport_to_tile_y = 6; t.transport_facing = 3; }
		{ Tile t = getTile(4, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(6, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(7, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(8, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(9, 4); t.tex = getMainWalkableTex(); t.walkable = true; t.transport_to_map = 0;
		t.transport_to_tile_x = 18; t.transport_to_tile_y = 6; t.transport_facing = 3; }
		{ Tile t = getTile(10, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(11, 4); t.tex = getMainWallTex(); t.walkable = false; }
	}

	public int getMainWalkableTex() {
		return 31;
	}
	public int getMainWallTex() {
		return 7;
	}

}
