package com.sweyla.gustavla.alone;

public class Inn extends Map {

	public String getName() {
		return "YOUR HOME";
	}
	
	public Inn(Engine engine) {
		// Generated by Python. I'm a bit new to Java, so I don't want to start parsing in Java
		super(engine, 7, 5);
		{ Tile t = getTile(0, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(4, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(6, 0); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(2, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 1); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 1); t.tex = 40; t.walkable = false; }
		{ Tile t = getTile(6, 1); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(2, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(3, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 2); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(6, 2); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 3); t.tex = getMainWalkableTex(); t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(1, 3); addEntity(unit); }
		{ Tile t = getTile(2, 3); t.tex = getMainWalkableTex(); t.walkable = true; Barrel unit = new Barrel(engine); unit.setTilePos(2, 3); addEntity(unit); }
		{ Tile t = getTile(3, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(4, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(5, 3); t.tex = getMainWalkableTex(); t.walkable = true; }
		{ Tile t = getTile(6, 3); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(0, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(1, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(2, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(3, 4); t.tex = getMainWalkableTex(); t.walkable = true; t.transport_to_map = 0;
		t.transport_to_tile_x = 12; t.transport_to_tile_y = 10; t.transport_facing = 1; }
		{ Tile t = getTile(4, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(5, 4); t.tex = getMainWallTex(); t.walkable = false; }
		{ Tile t = getTile(6, 4); t.tex = getMainWallTex(); t.walkable = false; }
	}
	
	
	public int getMainWalkableTex() {
		return 31;
	}
	public int getMainWallTex() {
		return 7;
	}
}
